export const CONFIG = {
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  QUIDAX_API_URL: process.env.NEXT_PUBLIC_QUIDAX_API_URL,
  QUIDAX_API_KEY: process.env.QUIDAX_API_KEY,
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
};